version: '3.7'

services:
  mysql:
    container_name: mysql_NEXT-AUTH
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nextauth
      MYSQL_USER: vsilva
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    container_name: adminer_nextauth
    ports:
      - "8080:8080"
    depends_on:
      - mysql

# volumes:
#   mysql-data: